id: "upstairs_hallway_motion_night_on"
alias: Upstairs hallway motion sensor night [on
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_1_motion_2
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - condition: state
    entity_id: light.upstairs_hallway
    state: "off"
action:
  - service: scene.turn_on
    target:
      entity_id: scene.upstairs_hallway_night
  - service: homeassistant.turn_on
    target:
      entity_id: input_boolean.automated_light_upstairs_hallway
mode: single
