id: "upstairs_hallway_motion_night_off"
alias: Upstairs hallway motion sensor night [off]
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_1_motion_2
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition:
  - condition: state
    entity_id: input_boolean.automated_light_upstairs_hallway
    state: "on"
action:
  - service: light.turn_off
    target:
      entity_id: light.upstairs_hallway
  - service: homeassistant.turn_off
    target:
      entity_id: input_boolean.automated_light_upstairs_hallway
mode: single
