sensor:
  unique_id: "next_sunrise"
  name: "Next sunrise"
  icon: mdi:weather-sunset-up
  state: >
    {% if is_state('sun.sun', 'below_horizon') %}
      {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M') }}
    {% else %}
      Unavailable
    {% endif %}
