living_room_appletv_tv_plus:
  alias: "Open Apple TV+"
  sequence:
    - service: remote.send_command
      target:
        entity_id: remote.living_room
      data:
        delay_secs: 1.5
        command:
          - top_menu
          - home
          - select
