id: 'entrance_light_on'
alias: Entrance light [on]
trigger:
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
action:
  - type: turn_on
    device_id: 6aad459fd72ca1be307874859184b639
    entity_id: light.hue_outdoor_wall_1
    domain: light
    brightness_pct: 50
mode: single
