id: "entrance_motion_on"
alias: Entrance motion sensor [on]
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_1_motion
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: light.hue_enrave_ceiling_1
    state: "off"
  - condition: numeric_state
    entity_id: sensor.hue_motion_sensor_1_illuminance
    below: 10
action:
  - service: light.turn_on
    target:
      entity_id: light.hue_enrave_ceiling_1
    data:
      brightness_pct: 30
  - service: homeassistant.turn_on
    target:
      entity_id: input_boolean.automated_light_entrance
mode: single
