id: "entrance_motion_off"
alias: Entrance motion sensor [off]
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_1_motion
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition:
  - condition: state
    entity_id: input_boolean.automated_light_entrance
    state: "on"
action:
  - service: light.turn_off
    target:
      entity_id: light.hue_enrave_ceiling_1
  - service: homeassistant.turn_off
    target:
      entity_id: input_boolean.automated_light_entrance
mode: single
