id: "entrance_motion_on"
alias: Entrance motion sensor [on]
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_1_motion
    from: "off"
    to: "on"
condition:
    - condition: state
      entity_id: light.hue_enrave_ceiling_1
      state: "off"
action:
  - type: turn_on
    device_id: f201b437290ee7bd19b11482173c490d
    entity_id: light.hue_enrave_ceiling_1
    domain: light
    brightness_pct: 30
mode: single
