title: "Default"
cards:
  - type: grid
    columns: 1
    square: false
    cards:
      - type: grid
        columns: 1
        square: false
        cards:
          - type: entities
            title: Family
            entities:
              - entity: !secret device_tracker_jesper
                name: Jesper
              - entity: !secret device_tracker_adrianna
                name: Adrianna
      - type: entities
        title: "Front door"
        entities:
          - entity: light.voordeur
      - type: entities
        title: "Entrance"
        entities:
          - entity: sensor.hue_motion_sensor_1_battery
            name: Motion sensor battery %
          - entity: light.hue_enrave_ceiling_1
          - entity: sensor.hue_motion_sensor_1_temperature
            name: "Entrance temperature"
      - type: grid
        columns: 1
        square: false
        title: "Living Room"
        cards:
          - type: thermostat
            entity: climate.woonkamer
          - type: entities
            title: "Lights"
            entities:
              - entity: light.eettafel
              - entity: light.bureau
              - entity: light.lounge
              - entity: light.tv
              - entity: light.plafondlamp
      - type: entity
        entity: sun.sun
        attribute: next_dusk

