title: "Printer"
cards:
  - type: grid
    columns: 1
    square: false
    cards:
      - type: entities
        title: "Ink levels"
        entities:
          - entity: sensor.canon_mg5300_series_black_bk
            tap_action:
              action: url
              url_path: https://www.123inkt.nl/Canon-CLI-526BK-inktcartridge-zwart-met-chip-123inkt-huismerk-4540B001C-i14455-t16748.html
          - entity: sensor.canon_mg5300_series_black_pgbk
            tap_action:
              action: url
              url_path: https://www.123inkt.nl/Canon-PGI-525PGBK-inktcartridge-zwart-met-chip-123inkt-huismerk-4529B001C-i14454-t16747.html
          - entity: sensor.canon_mg5300_series_cyan
            tap_action:
              action: url
              url_path: https://www.123inkt.nl/Canon-CLI-526C-inktcartridge-cyaan-met-chip-123inkt-huismerk-4541B001C-i14456-t16749.html
          - entity: sensor.canon_mg5300_series_magenta
            tap_action:
              action: url
              url_path: https://www.123inkt.nl/Canon-CLI-526M-inktcartridge-magenta-met-chip-123inkt-huismerk-4542B001C-i14457-t16750.html
          - entity: sensor.canon_mg5300_series_yellow
            tap_action:
              action: url
              url_path: https://www.123inkt.nl/Canon-CLI-526Y-inktcartridge-geel-met-chip-123inkt-huismerk-4543B001C-i14458-t16751.html
